---
title: "Assignment 9 - Publication-ready figures"
author: "Luke Henslee"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
---

```{r, include=FALSE, results=FALSE}
library(tidyverse)
library(ggplot2)
library(extrafont)
library(ggpubr)
library(forcats)
library(ggforce)
library(ggridges)
library(lubridate)
library(RColorBrewer)
library(viridis)
# Load fonts
loadfonts(device = "win")
```

### Figure 1  

#### 1) Import data   

```{r}
setwd("C:/Users/lhhenslee/Desktop/Luke/School/Coursework/635/data")

mcode <- read.csv("M_code_list.csv")
```

#### 2) Build plot  

```{r}
# Build 'glassplot'
glassplot <- ggplot(data = glass, aes(x = Length, y = Weight, fill = Class)) +
geom_point(shape = 21, size = 2) +
scale_y_continuous (limits = c(0,40), expand = c(0,0), breaks = seq(0,40,10)) +
scale_x_continuous(limits = c(10,60), expand = c(0,0), breaks = seq(10,60,10)) +
scale_fill_manual(limits = c("Green", "Brown"), labels = c("Green", "Brown"),
      values = c("black", "white")) +
ylab("Weight (g)") +
xlab("Length (mm)") +
labs(fill = "") +
theme_classic() +
theme (axis.title.y = element_text(size = 14, margin = margin(t = 0, r = 10, b = 0, l = 0), colour = "black"),
      axis.title.x = element_text(size = 14, margin = margin(t = 10, r = 0, b = 0, l = 0), colour = "black"),
      text = element_text(family = "Times New Roman"),
      legend.position = c(0.3,0.85),
      legend.text = element_text(size = 12),
      plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), "cm"),
      axis.ticks.y = element_line(size = 0.5),
      axis.ticks.x = element_line(size = 0.5),
      axis.ticks.length = unit(0.2,"cm"),
      axis.text.y = element_text(colour = "black", size = 14, angle = 0, vjust = 0.5, hjust = 1,
          margin = margin(t = 0, r = 5, b = 0, l = 0)),
      axis.text.x = element_text(colour = "black", size = 14, angle = 0, vjust = 0, hjust = 0.5,
          margin = margin(t = 5, r = 0, b = 0, l = 0)),
      axis.line = element_line(colour = "black", size = 0.5, lineend = "square"))
glassplot
```

#### 4) Save plot
```{r}
dev.new(width = 2.75, height = 1.83, units = "in", noRStudioGD = TRUE)
last_plot()

ggsave(file = "Pub_ready_figure_1_LH.tiff", width = dev.size()[1], height = dev.size()[2], dpi = 300)
```

#### 5) SLR on Weight ~ Length by color
```{r}
green <- glass %>% 
  filter(glass$Class == "Green")
brown <- glass %>% 
  filter(glass$Class == "Brown")
lmgreen <- lm(Weight ~ Length, data = green)
lmbrown <- lm(Weight ~ Length, data = brown)

```
#### 6) Add regression lines to plot
```{r}
glassplot_lm <- glassplot +
  geom_abline(slope = coef(lmgreen)[2], intercept = coef(lmgreen)[1]) +
  geom_abline(slope = coef(lmbrown)[2], intercept = coef(lmbrown)[1],
              linetype = "dashed") +
  stat_regline_equation(label.y = c(5, 18), label.x = c(38,28), aes(family = "Times New Roman"), data = glass)

glassplot_lm
```

#### 7) Save updated plot
```{r}
dev.new(width = 2.75, height = 1.83, units = "in", noRStudioGD = TRUE)
last_plot()

ggsave(file = "Pub_ready_figure_1b_LH.jpeg", width = dev.size()[1], height = dev.size()[2], dpi = 300)
dev.off()
```

### Figure 2

#### 1) Build plot  

```{r}
# Subset data to fish assigned to stocks
stocklength <- filter(mcode, mcode$Spawning.group %in% c("4", "5", "6", "S"))

# Build 'lengthdist'
lengthdist <- ggplot(data = stocklength, aes(x = Spawning.group, y = Length)) +
geom_boxplot() +
scale_y_continuous (limits = c(375,700), expand = c(0,0), breaks = seq(400,700,50)) +
ylab("Length (mm)") +
xlab("") +
labs(fill = "") +
theme_classic() +
theme (axis.title.y = element_text(size = 14, margin = margin(t = 0, r = 10, b = 0, l = 0), colour = "black"),
      axis.title.x = element_text(size = 14, margin = margin(t = 10, r = 0, b = 0, l = 0), colour = "black"),
      text = element_text(family = "Times New Roman"),
      legend.position = c(0.3,0.85),
      legend.text = element_text(size = 12),
      plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), "cm"),
      axis.ticks.y = element_line(size = 0.5),
      axis.ticks.x = element_line(size = 0.5),
      axis.ticks.length = unit(0.2,"cm"),
      axis.text.y = element_text(colour = "black", size = 14, angle = 0, vjust = 0.5, hjust = 1,
          margin = margin(t = 0, r = 5, b = 0, l = 0)),
      axis.text.x = element_text(colour = "black", size = 14, angle = 0, vjust = 0, hjust = 0.5,
          margin = margin(t = 5, r = 0, b = 0, l = 0)),
      axis.line = element_line(colour = "black", size = 0.5, lineend = "square"))
lengthdist
```

```{r}
stocklength2 <- filter(mcode, mcode$Spawning.group %in% c("5", "6", "S"))

lengthdistdens <- ggplot(data = stocklength2, aes(x = Length, fill = Spawning.group)) +
geom_density(alpha = 0.5, adjust = 1.5) +
scale_x_continuous (limits = c(375,700), expand = c(0,0), breaks = seq(400,700,50)) +
ylab("") +
xlab("") +
labs(fill = "") +
theme_classic() +
theme (axis.title.y = element_text(size = 14, margin = margin(t = 0, r = 10, b = 0, l = 0), colour = "black"),
      axis.title.x = element_text(size = 14, margin = margin(t = 10, r = 0, b = 0, l = 0), colour = "black"),
      text = element_text(family = "Times New Roman"),
      legend.position = c(0.3,0.85),
      legend.text = element_text(size = 12),
      plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), "cm"),
      axis.ticks.y = element_line(size = 0.5),
      axis.ticks.x = element_line(size = 0.5),
      axis.ticks.length = unit(0.2,"cm"),
      axis.text.y = element_text(colour = "black", size = 14, angle = 0, vjust = 0.5, hjust = 1,
          margin = margin(t = 0, r = 5, b = 0, l = 0)),
      axis.text.x = element_text(colour = "black", size = 14, angle = 0, vjust = 0, hjust = 0.5,
          margin = margin(t = 5, r = 0, b = 0, l = 0)),
      axis.line = element_line(colour = "black", size = 0.5, lineend = "square"))
lengthdistdens
```

#### 2) Save plot
```{r}
dev.new(width = 2.75, height = 1.83, units = "in", noRStudioGD = TRUE)
last_plot()

ggsave(file = "Pub_ready_figure_2_LH.jpeg", width = dev.size()[1], height = dev.size()[2], dpi = 300)
```

#### Multiple proportions 
```{r}
ggplot(stocklength, aes(x = yday(Date), y = ..count..)) +
  geom_density_line(data = select(stocklength, -Spawning.group), color = "transparent") +
  geom_density_line(fill = "red", color = "transparent") +
  facet_wrap(~Spawning.group, nrow = 2) +
  scale_x_continuous(name = "Day of year", limits = c(213,239), expand = c(0,0), breaks = seq(215,235,5))
```
```{r}
ggplot(stocklength, aes(x = yday(Date), y = ..count..)) +
  geom_density_line(data = select(stocklength, -Spawning.group), color = "transparent") +
  geom_density_line(aes(fill = fct_infreq(Spawning.group)), alpha = 0.5) +
  scale_x_continuous(name = "Day of year", limits = c(213,239), expand = c(0,0), breaks = seq(213,239,2))
```
```{r}
unk <- filter(stocklength, stocklength$Tag.group == 1)

shk <- filter(stocklength, stocklength$Tag.group == 2)
```
```{r}
ggplot(unk, aes(x = yday(Date), y = ..count..)) +
  geom_density_line(color = "transparent") +
  geom_density_line(aes(fill = fct_infreq(Spawning.group)), alpha = 0.5) +
  scale_x_continuous(name = "Day of year", limits = c(213,239), expand = c(0,0), breaks = seq(213,239,2))
```
```{r}
ggplot(shk, aes(x = yday(Date), y = ..count..)) +
  geom_density_line(color = "transparent") +
  geom_density_line(aes(fill = fct_infreq(Spawning.group)), alpha = 0.5) +
  scale_x_continuous(name = "Day of year", limits = c(213,239), expand = c(0,0), breaks = seq(213,239,2))
```
```{r}
ggplot(stocklength, aes(x = yday(Date), y = ..count..)) +
  geom_density_line(data = select(stocklength, -Spawning.group), color = "transparent") +
  geom_density_line(aes(fill = Spawning.group), color = "transparent") +
  facet_wrap(~Tag.group, nrow = 1) +
  scale_x_continuous(name = "Day of year", limits = c(213,239), expand = c(0,0), breaks = seq(215,235,5))
```
```{r}
ggplot(stocklength, aes(x = yday(Date), y = ..count..)) +
  geom_density_line(data = select(stocklength, -Spawning.group), color = "transparent", fill = "lightgrey") +
  geom_density_line(aes(fill = fct_infreq(Spawning.group)), alpha = 0.5, color = "black") +
  scale_x_continuous(name = "Day of year", limits = c(213,239), expand = c(0,0), breaks = seq(215,235,5)) +
  scale_y_continuous(name = "Count", expand = c(0, 0), limits = c(0, 22), breaks = seq(5, 20, 5)) +
  scale_fill_brewer(type = "qual", guide = "legend",
    palette = "Set2",
    name = "Stocks", breaks = c("6", "5", "4", "S"), 
    labels = c("Unalakleet", "Shaktoolik", "Norton Bay", "Yukon")) +
  theme(legend.position = c(0.7, 0.7)) +
  theme_classic()
```
```{r}
ggplot(stocklength, aes(x = yday(Date), y = ..count..)) +
  geom_density_line(data = select(stocklength, -Spawning.group), alpha = 0.5, color = "darkgrey", fill = "lightgrey", size = 0.5) +
  geom_density_line(aes(fill = fct_infreq(Spawning.group)), alpha = 0.5, color = "black", size = 0.5) +
  scale_x_continuous(name = "Day of year", limits = c(213,239), expand = c(0,0), breaks = seq(215,235,5)) +
  scale_y_continuous(name = "Count", expand = c(0, 0), limits = c(0, 22), breaks = seq(5, 20, 5)) +
  scale_fill_brewer(type = "qual", guide = "legend",
    palette = "Set2", name = "Stocks", breaks = c("6", "5", "4", "S"), 
    labels = c("Unalakleet", "Shaktoolik", "Norton Bay", "Yukon")) +
  theme_classic() +
theme (axis.title.y = element_text(size = 14, margin = margin(t = 0, r = 10, b = 0, l = 0), colour = "black"),
      axis.title.x = element_text(size = 14, margin = margin(t = 10, r = 0, b = 0, l = 0), colour = "black"),
      text = element_text(family = "Times New Roman"),
      legend.position = c(0.75,0.75),
      legend.text = element_text(size = 12),
      legend.title = element_text(size = 12),
      plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), "cm"),
      axis.ticks.y = element_line(size = 0.5),
      axis.ticks.x = element_line(size = 0.5),
      axis.ticks.length = unit(0.2,"cm"),
      axis.text.y = element_text(colour = "black", size = 14, angle = 0, vjust = 0.5, hjust = 1,
          margin = margin(t = 0, r = 5, b = 0, l = 0)),
      axis.text.x = element_text(colour = "black", size = 14, angle = 0, vjust = 0, hjust = 0.5,
          margin = margin(t = 5, r = 0, b = 0, l = 0)),
      axis.line = element_line(colour = "black", size = 0.5, lineend = "square"),
      panel.border = element_rect(color = "black", fill = "transparent", size = 0.5))
```
```{r}
dev.new(width = 2.75, height = 1.83, units = "in", noRStudioGD = TRUE)
last_plot()

ggsave(file = "Final_1b.tiff", width = dev.size()[1], height = dev.size()[2], dpi = 300)
```


```{r}

ggplot(stocklength, aes(x = yday(Date), y = ..count..)) +
  geom_density_line(data = select(stocklength, -Spawning.group), color = "transparent") +
  geom_density_line(aes(fill = fct_infreq(Spawning.group)), alpha = 0.5, color = "black") +
  scale_x_continuous(name = "Day of year", limits = c(213,239), expand = c(0,0), breaks = seq(213,239,2)) +
  scale_y_continuous(name = "Count", expand = c(0, 0)) +
  scale_fill_viridis(
    discrete = T,
    option = "C",
    name = "Stocks",
    guide = guide_legend(direction = "vertical")
  ) +
  coord_cartesian(clip = "off") +
  theme(
    axis.line.x = element_blank(),
    strip.text = element_text(size = 14, margin = margin(0, 0, 0.2, 0, "cm")),
    legend.position = "right",
    legend.justification = "right",
    legend.margin = margin(4.5, 0, 1.5, 0, "pt"),
    legend.spacing.x = grid::unit(4.5, "pt"),
    legend.spacing.y = grid::unit(0, "pt"),
    legend.box.spacing = grid::unit(0, "cm")
  )
```

```{r}
ggplot(mutate(df_health, health = fct_rev(health)), aes(x = age, y = ..count..)) +
  geom_density_line(data = select(df_health, -health), aes(fill = "all people surveyed   "), color = "transparent") +
  geom_density_line(aes(fill = "highlighted group"), color = "transparent") +
  facet_wrap(~health, nrow = 1) +
  scale_x_continuous(name = "age (years)", limits = c(15, 98), expand = c(0, 0)) +
  scale_y_continuous(name = "count", expand = c(0, 0)) +
  scale_fill_manual(
    values = c("#b3b3b3a0", "#2b8cbed0"),
    name = NULL,
    guide = guide_legend(direction = "horizontal")
  ) +
  coord_cartesian(clip = "off") +
  theme_dviz_hgrid() +
  theme(
    axis.line.x = element_blank(),
    strip.text = element_text(size = 14, margin = margin(0, 0, 0.2, 0, "cm")),
    legend.position = "bottom",
    legend.justification = "right",
    legend.margin = margin(4.5, 0, 1.5, 0, "pt"),
    legend.spacing.x = grid::unit(4.5, "pt"),
    legend.spacing.y = grid::unit(0, "pt"),
    legend.box.spacing = grid::unit(0, "cm")
  )
```
# Figure 2 

```{r}
library(rnaturalearth)
library(rnaturalearthdata)
library(ggspatial)
library(sf)

world <- ne_countries(scale = "medium", returnclass = "sf")
ggplot(data = world) +
        theme_classic() +  
        geom_sf() +
        coord_sf(xlim = c(-161.5, -160.5), ylim = c(63.5, 64.5), expand = TRUE)  +
        geom_point(data=stocklength,
                   aes(x=Long, y=Lat, color=Spawning.group), alpha=0.5) +
        scale_color_viridis(discrete = TRUE, option = "C") 
```
```{r}
map.dat <- get_map(location=c(-161.6, 64.1,
                              -160.75, 64.5),
                   maptype='toner-lite', source='stamen', crop=TRUE)
```
```{r}
ggmap(map.dat) +
        theme_linedraw() +  
        geom_point(data=shk,
                   aes(x=Long, y=Lat, color=Spawning.group, size = 12, alpha = 0.5)) +
        scale_color_viridis(discrete = TRUE, option = "C") 
```

