---
title: "Final project "
author: "Luke Henslee"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
---

```{r, include=FALSE, results=FALSE}

library(ggpubr)
library(forcats)
library(ggforce)
library(lubridate)
library(RColorBrewer)
library(viridis)
library(tidyverse)
library(ggplot2)
library(bbmle)
library(dplyr)
library(manipulate)
library(visreg) 
library(ggthemes)
library(ggridges)
library(reshape2)
library(cowplot)
library(ggmap)
library(ggspatial)
library(sf)
library(spData)
library(ggsn)
library(extrafont)
loadfonts(device = "win")

```

### Figure 1  

#### 1) Import data   

```{r}
setwd("C:/Users/lhhenslee/Desktop/Luke/School/Coursework/635/data")

mcode <- read.csv("M_code_list.csv")
```

#### 2) Build plot  

```{r}
# Subset data to fish assigned to stocks
stocklength <- filter(mcode, mcode$Spawning.group %in% c("4", "5", "6", "S"))

# Build 'lengthdist'
lengthdist <- ggplot(data = stocklength, aes(x = Spawning.group, y = Length)) +
geom_boxplot() +
scale_y_continuous (limits = c(375,700), expand = c(0,0), breaks = seq(400,700,50)) +
ylab("Length (mm)") +
xlab("") +
labs(fill = "") +
theme_classic() +
theme (axis.title.y = element_text(size = 14, margin = margin(t = 0, r = 10, b = 0, l = 0), colour = "black"),
      axis.title.x = element_text(size = 14, margin = margin(t = 10, r = 0, b = 0, l = 0), colour = "black"),
      text = element_text(family = "Times New Roman"),
      legend.position = c(0.3,0.85),
      legend.text = element_text(size = 12),
      plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), "cm"),
      axis.ticks.y = element_line(size = 0.5),
      axis.ticks.x = element_line(size = 0.5),
      axis.ticks.length = unit(0.2,"cm"),
      axis.text.y = element_text(colour = "black", size = 14, angle = 0, vjust = 0.5, hjust = 1,
          margin = margin(t = 0, r = 5, b = 0, l = 0)),
      axis.text.x = element_text(colour = "black", size = 14, angle = 0, vjust = 0, hjust = 0.5,
          margin = margin(t = 5, r = 0, b = 0, l = 0)),
      axis.line = element_line(colour = "black", size = 0.5, lineend = "square"))
lengthdist
```

### Figure 2

#### 1) Lubridate
```{r}
stocklength$Date <- mdy(stocklength$Date)
```

#### 2) Build plot
```{r}
ggplot(stocklength, aes(x = yday(Date), y = ..count..)) +
  geom_density_line(data = select(stocklength, -Spawning.group), alpha = 0.5, color = "darkgrey", fill = "lightgrey", size = 0.5) +
  geom_density_line(aes(fill = fct_infreq(Spawning.group)), alpha = 0.5, color = "black", size = 0.5) +
  scale_x_continuous(name = "Day of year", limits = c(213,239), expand = c(0,0), breaks = seq(215,235,5)) +
  scale_y_continuous(name = "Count", expand = c(0, 0), limits = c(0, 22), breaks = seq(5, 20, 5)) +
  scale_fill_brewer(type = "qual", guide = "legend",
    palette = "Set2", name = "Stocks", breaks = c("6", "5", "4", "S"), 
    labels = c("Unalakleet", "Shaktoolik", "Norton Bay", "Yukon")) +
  theme_classic() +
theme (axis.title.y = element_text(size = 14, margin = margin(t = 0, r = 10, b = 0, l = 0), colour = "black"),
      axis.title.x = element_text(size = 14, margin = margin(t = 10, r = 0, b = 0, l = 0), colour = "black"),
      text = element_text(family = "Times New Roman"),
      legend.position = c(0.75,0.75),
      legend.text = element_text(size = 12),
      legend.title = element_text(size = 12),
      plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), "cm"),
      axis.ticks.y = element_line(size = 0.5),
      axis.ticks.x = element_line(size = 0.5),
      axis.ticks.length = unit(0.2,"cm"),
      axis.text.y = element_text(colour = "black", size = 14, angle = 0, vjust = 0.5, hjust = 1,
          margin = margin(t = 0, r = 5, b = 0, l = 0)),
      axis.text.x = element_text(colour = "black", size = 14, angle = 0, vjust = 0, hjust = 0.5,
          margin = margin(t = 5, r = 0, b = 0, l = 0)),
      axis.line = element_line(colour = "black", size = 0.5, lineend = "square"),
      panel.border = element_rect(color = "black", fill = "transparent", size = 0.5))
```

# Figure 3


